import './globals.css'
import { Inter } from 'next/font/google'

import NavbarComp from '@/app/components/Navbar'
import Provider from './components/Provider'
import { AuthProvider } from '@/firebase/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NavbarComp />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
